name: Build and Deploy

on:
  push:
    branches:
      - master # or your default branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    # Setting up Docker Buildx (for multi-platform support and better caching)
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build Docker Compose
      run: docker-compose build

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
<<<<<<< HEAD
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
=======
        password: ${{ secrets.DOCKER_HUB_TOKEN }}

>>>>>>> 8cc5d7721bb40b90c588cacc5c735fa9153bb208

    # Pushing the Docker images
    - name: Push Docker images
      run: |
        docker-compose push

    # (Optional) If you want to also deploy the stack after pushing, you can use:
    # - name: Deploy with Docker Compose
    #   run: |
    #     docker-compose up -d
