name: Build and Deploy

on:
  push:
    branches:
      - master # or your default branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    # Setting up Docker Buildx (for multi-platform support and better caching)
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build Docker Compose
      run: docker-compose build

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    # Pushing the Docker images
    - name: Push Docker images
      run: |
        docker-compose push

    # Setup SSH key for Lightsail deployment
    - name: Setup SSH key
      run: |
        echo "${{ secrets.LIGHTSAIL_SSH_KEY }}" > deploy_key.pem
        chmod 600 deploy_key.pem

    # Deploy to AWS Lightsail
    - name: Deploy to Lightsail
      run: |
        ssh -i deploy_key.pem -o StrictHostKeyChecking=no ubuntu@3.18.85.144 "docker-compose pull && docker-compose build --no-cache && docker-compose up -d
"
